// Social Media Broadcast Cron — daily autopilot
// Fetches top trending item + latest blog post, formats platform-specific messages.
// GET /api/cron/social-broadcast

import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { checkCronAuth, unauthorizedResponse, logCronJob, logError, getTopTrendingItems } from '@/lib/cron-utils'

export const dynamic = 'force-dynamic'
export const maxDuration = 120

const SITE_URL = 'https://ainextgrowth.com'

export async function GET(req: NextRequest) {
  if (!checkCronAuth(req)) return unauthorizedResponse()
  const t0 = Date.now()

  try {
    // Fetch top trending item
    const trendingItems = await getTopTrendingItems(1)
    const topItem = trendingItems[0]

    // Fetch latest blog post
    const latestArticle = await db.article.findFirst({
      orderBy: { publishedAt: 'desc' },
      select: { slug: true, title: true, metaDescription: true, category: true },
    })

    // Get connected social integrations
    const integrations = await db.socialIntegration.findMany({
      where: { connected: true, autoPost: true },
    })

    if (integrations.length === 0) {
      const duration = Date.now() - t0
      await logCronJob('social-broadcast', 'completed', duration, 0, 'No connected social platforms')
      return NextResponse.json({ success: true, message: 'No connected social platforms', sentTo: 0 })
    }

    let sentCount = 0
    const results: { platform: string; status: string; message: string }[] = []

    for (const integration of integrations) {
      try {
        let message = ''

        if (integration.platform === 'twitter') {
          // Short text + link for X (Twitter) — max 280 chars
          if (topItem) {
            message = `🔥 Trending AI ${topItem.type} today:\n\n"${topItem.title}"\n\nRead & download → ${SITE_URL}/?item=${topItem.slug}\n\n#AI #PromptEngineering #2026`
          } else {
            message = `🚀 New AI insights on ainextgrowth!\n\n${latestArticle?.title || 'Check our latest content'}\n\n${SITE_URL}/blog`
          }
        } else if (integration.platform === 'linkedin') {
          // Long-form post for LinkedIn
          message = `🚀 AI Trend Alert from ainextgrowth\n\n`
          if (topItem) {
            message += `Today's top trending ${topItem.type}: "${topItem.title}"\n\n`
            message += `${topItem.niche} · ★ ${topItem.trendingScore} trending score\n\n`
            message += `Download the Trinity Bundle (Prompt + Workflow + Audience) → ${SITE_URL}/?item=${topItem.slug}\n\n`
          }
          if (latestArticle) {
            message += `📚 Latest article: "${latestArticle.title}"\n${SITE_URL}/blog/${latestArticle.slug}\n\n`
          }
          message += `#AI #ArtificialIntelligence #PromptEngineering #Automation #2026`
        } else if (integration.platform === 'reddit') {
          // Markdown for Reddit
          message = `**🔥 Daily AI Trend from ainextgrowth**\n\n`
          if (topItem) {
            message += `**${topItem.title}**\n\n`
            message += `> ${topItem.niche} · Trending score: ${topItem.trendingScore}\n\n`
            message += `[Download Trinity Bundle](${SITE_URL}/?item=${topItem.slug})\n\n`
          }
          if (latestArticle) {
            message += `**Latest Article:** [${latestArticle.title}](${SITE_URL}/blog/${latestArticle.slug})\n\n`
          }
          message += `---\n*Generated by ainextgrowth autonomous agent*`
        } else if (integration.platform === 'telegram') {
          // Markdown for Telegram
          message = `🔥 *Daily AI Trend from ainextgrowth*\n\n`
          if (topItem) {
            message += `*${topItem.title}*\n`
            message += `📂 ${topItem.niche} | ⭐ ${topItem.trendingScore}\n`
            message += `🔗 ${SITE_URL}/?item=${topItem.slug}\n\n`
          }
          if (latestArticle) {
            message += `📚 *New Article:* ${latestArticle.title}\n`
            message += `🔗 ${SITE_URL}/blog/${latestArticle.slug}\n\n`
          }
          message += `— ainextgrowth`
        }

        // Mock posting to platform (in production, use real API):
        // if (integration.platform === 'twitter') {
        //   const client = new TwitterApi(integration.accessToken)
        //   await client.v2.tweet(message)
        // }

        console.log(`[Social Broadcast] ${integration.platform}: ${message.slice(0, 80)}...`)

        await db.socialIntegration.update({
          where: { id: integration.id },
          data: { lastPostedAt: new Date() },
        })

        sentCount++
        results.push({ platform: integration.platform, status: 'success', message: message.slice(0, 80) })
      } catch (e: any) {
        results.push({ platform: integration.platform, status: 'failed', message: e?.message || 'Unknown error' })
      }
    }

    const duration = Date.now() - t0
    await logCronJob('social-broadcast', 'completed', duration, sentCount, `Posted to ${sentCount}/${integrations.length} platforms`)

    return NextResponse.json({
      success: true,
      sentTo: sentCount,
      totalPlatforms: integrations.length,
      results,
      contentPreview: {
        topItem: topItem?.title || null,
        latestArticle: latestArticle?.title || null,
      },
      durationMs: duration,
      timestamp: new Date().toISOString(),
    })
  } catch (e: any) {
    const duration = Date.now() - t0
    await logError('cron', '/api/cron/social-broadcast', e?.message || 'Unknown error', e?.stack || '')
    await logCronJob('social-broadcast', 'failed', duration, 0, e?.message || 'Unknown error')
    return NextResponse.json({ success: false, error: e?.message }, { status: 500 })
  }
}
